
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/thijm/AppData/Local/JetBrains/Toolbox/apps/CLion/ch-0/232.8660.186/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
...
